# Generated by Django 2.2.7 on 2019-11-18 17:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('agent_id', models.IntegerField()),
                ('phone_number', models.TextField(max_length=20)),
                ('agent_email', models.TextField(max_length=100)),
                ('company_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('phone_number', models.TextField(max_length=20)),
                ('company_email', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.CharField(max_length=50)),
                ('listing_id', models.IntegerField()),
                ('price', models.TextField(max_length=20)),
                ('rent', models.TextField(max_length=20)),
                ('agent_id', models.IntegerField()),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
