# Generated by Django 2.2.7 on 2019-11-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertymatching', '0002_auto_20191124_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingitem',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
