# Generated by Django 2.2.7 on 2019-11-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertymatching', '0002_auto_20191118_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='listing_item',
            old_name='agent_id',
            new_name='agent',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='agent_id',
        ),
        migrations.RemoveField(
            model_name='listing_item',
            name='listing_id',
        ),
    ]
