# Generated by Django 2.2.7 on 2019-12-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertymatching', '0003_auto_20191126_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingitem',
            name='monthly_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='listingitem',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
