# Generated by Django 2.2.7 on 2019-11-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertymatching', '0003_auto_20191118_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing_item',
            old_name='rent',
            new_name='monthly_cost',
        ),
    ]
