# Generated by Django 2.2.7 on 2019-12-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertymatching', '0004_auto_20191207_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='propertymatching.ListingItem')),
                ('userform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='propertymatching.UserForm')),
            ],
        ),
    ]
